name: ECS Deployment

on:
  workflow_dispatch:
    inputs:
      terraform_action:
        type: choice
        description: Select Terraform Action
        options:
          - apply
          - destroy
        required: true
  push:
    branches: [ "main" ]

env:
  AWS_REGION: us-east-1

jobs:
  terraform:
    name: 'Terraform Apply/Destroy'
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_DEVOPS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_DEVOPS_SECRET_ACCESS_KEY }}
          aws-region: ${{ env.AWS_REGION }}

      - name: Terraform Init
        uses: hashicorp/terraform-github-actions@master
        with:
          tf_actions_version: '1.1.7'
          tf_actions_subcommand: 'init'
          tf_actions_working_dir: './infra'
          tf_actions_comment: true

      - name: Terraform Validate
        uses: hashicorp/terraform-github-actions@master
        with:
          tf_actions_version: '1.1.7'
          tf_actions_subcommand: 'validate'
          tf_actions_working_dir: './infra'
          tf_actions_comment: true

      - name: Terraform Plan
        uses: hashicorp/terraform-github-actions@master
        with:
          tf_actions_version: '1.1.7'
          tf_actions_subcommand: 'plan'
          tf_actions_working_dir: './infra'
          tf_actions_comment: true
          args: '-out=plan.tfplan'

      - name: Terraform Apply/Destroy
        uses: hashicorp/terraform-github-actions@master
        with:
          tf_actions_version: '1.1.7'
          tf_actions_subcommand: ${{ github.event.inputs.terraform_action }}
          tf_actions_working_dir: './infra'
          tf_actions_comment: true
          args: ${{ github.event.inputs.terraform_action == 'apply' && '-auto-approve -input=false plan.tfplan' || '-auto-approve' }}