name: Deploy to ECS

on:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      
      - name: Configure AWS Credentials for Terraform
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.5.0

      - name: Terraform Init & Apply
        working-directory: ./infra
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_DEFAULT_REGION: us-east-1
        run: |
          terraform init
          terraform apply -auto-approve

      - name: Get Terraform Outputs
        id: tf_outputs
        working-directory: ./infra
        run: |
          echo "task_def=$(terraform output -raw task_definition_family | tr -d '\r\n' | sed 's/::debug::.*//')" >> $GITHUB_OUTPUT
          echo "ecs_svc=$(terraform output -raw ecs_service_name | tr -d '\r\n' | sed 's/::debug::.*//')" >> $GITHUB_OUTPUT
          echo "ecs_clust=$(terraform output -raw ecs_cluster_name | tr -d '\r\n' | sed 's/::debug::.*//')" >> $GITHUB_OUTPUT

      - name: Deploy to ECS
        uses: aws-actions/amazon-ecs-deploy-task-definition@v2
        with:
          task-definition: ${{ steps.tf_outputs.outputs.task_def }}
          service: ${{ steps.tf_outputs.outputs.ecs_svc }}
          cluster: ${{ steps.tf_outputs.outputs.ecs_clust }}
